name: Build

on:
  pull_request:
    branches: [ "main", "develop", "feat/*", "refactor/*", "release/*", "ci/*", "fix/*" ]
    types: [ "opened", "reopened", "synchronize" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.head_ref }}
  cancel-in-progress: true

jobs:
  build-debug:
    name: Build Debug
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Set up JDK 17
        uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4.8.0
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Assemble debug builds
        run: |
          ./gradlew \
            :core:assemble \
            :android:assembleDebug \
            :integrations:adjust:assembleDebug \
            :integrations:appsflyer:assembleDebug \
            :integrations:firebase:assembleDebug \
            :integrations:facebook:assembleDebug \
            :integrations:braze:assembleDebug

  build-release:
    name: Build Release
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Set up JDK 17
        uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4.8.0
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Assemble release builds
        run: |
          ./gradlew \
            :core:assemble \
            :android:assembleRelease \
            :integrations:adjust:assembleRelease \
            :integrations:appsflyer:assembleRelease \
            :integrations:firebase:assembleRelease \
            :integrations:facebook:assembleRelease \
            :integrations:braze:assembleRelease
